"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useEffect, useState } from "react";
import { Toaster } from "@/components/ui/toaster";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const interDisplay = localFont({
  src: [
    {
      path: '../public/fonts/InterDisplay-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/InterDisplay-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/InterDisplay-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient()


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isDesktop, setIsDesktop] = useState(false)

  useEffect(() => {
    const checkDevice = () => {
      setIsDesktop(window.innerWidth >= 768)
    }

    checkDevice()
    window.addEventListener("resize", checkDevice)
    return () => window.removeEventListener("resize", checkDevice)
  }, [])
  return (
    <html lang="en">
      <body
        className={`${interDisplay.className} antialiased`}
      >
        <Dialog open={isDesktop}>
        <DialogContent className="bg-white">
          <DialogHeader>
            <DialogTitle>Mobile Only Application</DialogTitle>
            <DialogDescription>
              This application is only available on mobile devices. Please access it from your smartphone or tablet.
            </DialogDescription>
          </DialogHeader>
        </DialogContent>
      </Dialog>
      <QueryClientProvider client={queryClient}>
      <main className="min-h-screen max-w-md mx-auto bg-white">
        {children}
        <Toaster />
      </main>
      </QueryClientProvider>
      </body>
    </html>
  );
}
